-- Create the table
create table punchlines (
  id bigint generated by default as identity primary key,
  content text not null,
  track_title text,
  genius text,
  upvotes bigint default 0,
  downvotes bigint default 0,
  score bigint generated always as (upvotes - downvotes) stored,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) if you want to restrict access, 
-- but for this public app we might want to allow public reads and RPC calls for voting.
-- For simplicity in this prototype, we will allow public read/write via API logic or policies.

-- Policy to allow everyone to read
alter table punchlines enable row level security;

create policy "Enable read access for all users"
on punchlines for select
to anon
using (true);

-- We generally don't want direct UPDATE access for anon users to prevent arbitrary editing.
-- Instead, we should use Database Functions (RPC) for upvoting/downvoting to ensure atomic increments.

create or replace function vote_punchline(punchline_id bigint, up_delta int, down_delta int)
returns void
language plpgsql
security definer
as $$
begin
  update punchlines
  set 
    upvotes = upvotes + up_delta,
    downvotes = downvotes + down_delta
  where id = punchline_id;
end;
$$;

-- Seed data
insert into punchlines (content, track_title, genius, upvotes, downvotes) values
('J''ai le cœur glacé comme un hiver à Montréal', 'Hiver', 'https://genius.com/Nekfeu-hiver-lyrics', 10, 2),
('Le succès c''est pas la chute, c''est le rebond', 'Rebond', 'https://genius.com/Booba-rebond-lyrics', 25, 1),
('Ils parlent de rue, je leur parle de bitume', 'Bitume', 'https://genius.com/Rohff-bitume-lyrics', 5, 5),
('L''argent n''a pas d''odeur mais la pauvreté pue', 'Réalité', 'https://genius.com/Kery-james-realite-lyrics', 50, 3),
('Je vise la lune, au pire je tombe dans les étoiles', 'Astronaute', 'https://genius.com/Oscar-wilde-citation', 100, 10),
('Mon silence fait plus de bruit que tes cris', 'Silence', 'https://genius.com/Damso-silence-lyrics', 15, 0),
('Chaque cicatrice est une leçon tatouée', 'Leçon', 'https://genius.com/Booba-lecon-lyrics', 30, 4),
('Le temps passe, les vrais restent', 'Temps', 'https://genius.com/Ninho-temps-lyrics', 45, 2),
('Je suis pas né pour plaire, je suis né pour être vrai', 'Authentique', 'https://genius.com/Jul-authentique-lyrics', 60, 5),
('La vie c''est un risque, la mort une certitude', 'Risque', 'https://genius.com/Orelsan-risque-lyrics', 80, 8);
